[0m13:54:12.921225 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab49a5b5400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab49a3b1ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab49affa330>]}


============================== 13:54:12.928792 | 2e0f1d41-a426-4efe-90bb-a8945301b95e ==============================
[0m13:54:12.928792 [info ] [MainThread]: Running with dbt=1.9.0
[0m13:54:12.929525 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/root/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init my_project', 'send_anonymous_usage_stats': 'True'}
[0m13:54:12.968696 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/root/.dbt')}
[0m13:54:12.969298 [info ] [MainThread]: Creating dbt configuration folder at 
[0m13:54:12.970972 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.12/site-packages/dbt/include/starter_project
[0m13:54:12.974170 [info ] [MainThread]: 
Your new dbt project "my_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:54:12.974563 [info ] [MainThread]: Setting up your profile.
[0m13:55:19.332030 [info ] [MainThread]: Profile my_project written to /root/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:55:19.335903 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 69.21861, "process_in_blocks": "168", "process_kernel_time": 0.178741, "process_mem_max_rss": "92788", "process_out_blocks": "1544", "process_user_time": 1.236293}
[0m13:55:19.336707 [debug] [MainThread]: Command `dbt init` succeeded at 13:55:19.336543 after 69.22 seconds
[0m13:55:19.337238 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab49a6f2930>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab49a12d3a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ab49a5b5820>]}
[0m13:55:19.337778 [debug] [MainThread]: Flushing usage events
[0m13:55:20.975411 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:56:33.259202 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x736e6b3deab0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x736e6c864470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x736e6b3dfd70>]}


============================== 13:56:33.267837 | d0899eb4-36d6-49ce-8d66-03f88854d1b1 ==============================
[0m13:56:33.267837 [info ] [MainThread]: Running with dbt=1.9.0
[0m13:56:33.268456 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init my_project', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:56:33.319471 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/root/.dbt')}
[0m13:56:33.320723 [info ] [MainThread]: Creating dbt configuration folder at 
[0m13:56:33.322487 [info ] [MainThread]: A project called my_project already exists here.
[0m13:56:33.325585 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.12049331, "process_in_blocks": "2696", "process_kernel_time": 0.176053, "process_mem_max_rss": "86964", "process_out_blocks": "1480", "process_user_time": 1.236041}
[0m13:56:33.326196 [debug] [MainThread]: Command `dbt init` succeeded at 13:56:33.326065 after 0.12 seconds
[0m13:56:33.326534 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x736e6b3bb860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x736e6ae0f140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x736e6ae6e150>]}
[0m13:56:33.326871 [debug] [MainThread]: Flushing usage events
[0m13:56:34.638620 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:57:41.422867 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e099155b830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e09916175f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e099155b890>]}


============================== 13:57:41.431455 | 8d3ce44d-7393-4783-93be-12fad1035f82 ==============================
[0m13:57:41.431455 [info ] [MainThread]: Running with dbt=1.9.0
[0m13:57:41.432022 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m13:57:41.473141 [info ] [MainThread]: dbt version: 1.9.0
[0m13:57:41.473595 [info ] [MainThread]: python version: 3.12.4
[0m13:57:41.473899 [info ] [MainThread]: python path: /usr/local/bin/python
[0m13:57:41.474174 [info ] [MainThread]: os info: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31
[0m13:57:41.474458 [info ] [MainThread]: Using profiles dir at /root/.dbt
[0m13:57:41.474729 [info ] [MainThread]: Using profiles.yml file at /root/.dbt/profiles.yml
[0m13:57:41.474980 [info ] [MainThread]: Using dbt_project.yml file at /usr/app/dbt_project.yml
[0m13:57:41.475221 [info ] [MainThread]: Configuration:
[0m13:57:41.475473 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m13:57:41.475717 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:57:41.475977 [info ] [MainThread]: Required dependencies:
[0m13:57:41.476257 [debug] [MainThread]: Executing "git --help"
[0m13:57:41.487745 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone             Clone a repository into a new directory\n   init              Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add               Add file contents to the index\n   mv                Move or rename a file, a directory, or a symlink\n   restore           Restore working tree files\n   rm                Remove files from the working tree and from the index\n   sparse-checkout   Initialize and modify the sparse-checkout\n\nexamine the history and state (see also: git help revisions)\n   bisect            Use binary search to find the commit that introduced a bug\n   diff              Show changes between commits, commit and working tree, etc\n   grep              Print lines matching a pattern\n   log               Show commit logs\n   show              Show various types of objects\n   status            Show the working tree status\n\ngrow, mark and tweak your common history\n   branch            List, create, or delete branches\n   commit            Record changes to the repository\n   merge             Join two or more development histories together\n   rebase            Reapply commits on top of another base tip\n   reset             Reset current HEAD to the specified state\n   switch            Switch branches\n   tag               Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch             Download objects and refs from another repository\n   pull              Fetch from and integrate with another repository or a local branch\n   push              Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m13:57:41.488228 [debug] [MainThread]: STDERR: "b''"
[0m13:57:41.488484 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m13:57:41.488776 [info ] [MainThread]: Connection test skipped since no profile was found
[0m13:57:41.489098 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:57:41.489391 [info ] [MainThread]: dbt looked for a profiles.yml file in /root/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m13:57:41.489647 [info ] [MainThread]: Project loading failed for the following reason:
 project path </usr/app/dbt_project.yml> not found

[0m13:57:41.490634 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.18747693, "process_in_blocks": "88", "process_kernel_time": 0.21827, "process_mem_max_rss": "86620", "process_out_blocks": "1480", "process_user_time": 1.233039}
[0m13:57:41.492250 [debug] [MainThread]: Command `dbt debug` failed at 13:57:41.491673 after 0.19 seconds
[0m13:57:41.492679 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e0990f16840>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e0990e227e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e09912567e0>]}
[0m13:57:41.493123 [debug] [MainThread]: Flushing usage events
[0m13:57:43.173271 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:25:33.532520 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dc80dfe1e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dc80f8f380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dc810e10a0>]}


============================== 09:25:33.540461 | 1a325e5f-f60a-45da-bdfd-a7cace26d27f ==============================
[0m09:25:33.540461 [info ] [MainThread]: Running with dbt=1.9.0
[0m09:25:33.541018 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/root/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:25:33.541414 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /root/.dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:25:33.542384 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.06503824, "process_in_blocks": "112", "process_kernel_time": 0.13426, "process_mem_max_rss": "86460", "process_out_blocks": "1472", "process_user_time": 1.219852}
[0m09:25:33.542856 [debug] [MainThread]: Command `dbt run` failed at 09:25:33.542756 after 0.07 seconds
[0m09:25:33.543157 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dc8082fe90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dc83fba8a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75dc83fba8d0>]}
[0m09:25:33.543486 [debug] [MainThread]: Flushing usage events
[0m09:25:34.763016 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:25:54.822064 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72c1d49ada00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72c1d4745370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72c1d4bae330>]}


============================== 09:25:54.830267 | 510d5b07-a500-44ef-b928-ca035a095951 ==============================
[0m09:25:54.830267 [info ] [MainThread]: Running with dbt=1.9.0
[0m09:25:54.831018 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m09:25:54.831745 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /root/.dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:25:54.832905 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.063373804, "process_in_blocks": "0", "process_kernel_time": 0.165138, "process_mem_max_rss": "86640", "process_out_blocks": "1480", "process_user_time": 1.286544}
[0m09:25:54.833364 [debug] [MainThread]: Command `dbt run` failed at 09:25:54.833270 after 0.06 seconds
[0m09:25:54.833657 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72c1d46520c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72c1d4745370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72c1d4420f20>]}
[0m09:25:54.833981 [debug] [MainThread]: Flushing usage events
[0m09:25:56.207878 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:29:09.343313 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7007c36d5ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7007c1c9e360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7007c1875640>]}


============================== 09:29:09.349747 | d996ef27-0503-468a-811a-77fefd13dc96 ==============================
[0m09:29:09.349747 [info ] [MainThread]: Running with dbt=1.9.0
[0m09:29:09.350205 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:29:09.350530 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /root/.dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:29:09.351308 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.053561624, "process_in_blocks": "0", "process_kernel_time": 0.159927, "process_mem_max_rss": "86476", "process_out_blocks": "1472", "process_user_time": 1.267995}
[0m09:29:09.351768 [debug] [MainThread]: Command `dbt run` failed at 09:29:09.351679 after 0.05 seconds
[0m09:29:09.352026 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7007c252fb60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7007c1875640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7007c4fde8d0>]}
[0m09:29:09.352298 [debug] [MainThread]: Flushing usage events
[0m09:29:10.761434 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:29:12.762941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ff84700200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ff847018b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ff84700260>]}


============================== 09:29:12.769260 | 3bc03b31-f555-4f61-a8f5-21aad2b6299d ==============================
[0m09:29:12.769260 [info ] [MainThread]: Running with dbt=1.9.0
[0m09:29:12.770215 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:29:12.770691 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /root/.dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:29:12.771550 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.050733477, "process_in_blocks": "0", "process_kernel_time": 0.171177, "process_mem_max_rss": "86200", "process_out_blocks": "1472", "process_user_time": 0.99283}
[0m09:29:12.771951 [debug] [MainThread]: Command `dbt run` failed at 09:29:12.771868 after 0.05 seconds
[0m09:29:12.772202 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ff84e4e6f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ff8559df70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ff846bf860>]}
[0m09:29:12.772461 [debug] [MainThread]: Flushing usage events
[0m09:29:12.584555 [debug] [MainThread]: An error was encountered while trying to flush usage events
